name: generate pacman game

on:
  schedule:
    # run automatically every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:
    # allows to manually run the job at any time
  push:
    # run on every push on the main branch
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step to check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to generate the SVG file
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ilful360 # Your username provided as a string

      # Step to push the generated SVG to the 'output' branch
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          # build_dir: dist # Removed this; the file is generated in the root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
